imflipPMC	:	imflipPMC.c ImageStuff.c ImageStuff.h
				gcc imflipPMC.c ImageStuff.c -o imflipPMC -lpthread -Wformat -Wall

imrotateMMC	:	imrotateMMC.c ImageStuff.c ImageStuff.h
				gcc imrotateMMC.c ImageStuff.c -o imrotateMMC -lpthread -lm -Wformat -Wall
				